// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Resources;

/************************************************************/
/**
 * 
 */
public class City extends Structure implements Purchasable {
	/**
	 * 
	 */
	private static int MAX = 4;

	/**
	 * 
	 * @return 
	 */
	public Cost getCost() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}
}
