// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Resources;

/************************************************************/
/**
 * 
 */
public class Cost {
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int lumber;
	/**
	 * 
	 */
	private int grain;
	/**
	 * 
	 */
	private int wool;
	/**
	 * 
	 */
	private int ore;
}
