// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Resources;

/************************************************************/
/**
 * 
 */
public class Road implements Purchasable {
	/**
	 * 
	 */
	private static int MAX = 15;

	/**
	 * 
	 * @return 
	 */
	public Cost getCost() {
	}
}
