// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Resources;

/************************************************************/
/**
 * Represents a Road that a player can build in the game.
 * A Road is a type of Structure worth 0 victory points, and
 * it has a fixed resource cost so other parts of the system can
 * query it through the Purchasable interface.
 * @author Parnia Yazdinia, 400567795, McMaster University
 */
public class Road extends Structure implements Purchasable {
    /** Maximum number of Roads a player can build */
	private static final int MAX = 15;

    /**
     * Returns the resource cost required to build one Road
     * @return the required cost
     */
    @Override
	public Cost getCost() {
        //1 BRICK, 1 LUMBER, 0 GRAIN, 0 WOOL, 0 ORE
        return new Cost(1, 1, 0, 0, 0);
	}

    /**
     * Returns the number of victory points a Road provides
     * @return Victory points gained from this Road (0)
     */
    @Override
    public int getVictoryPoints() {
        return 0;
    }

    /**
     * Returns the maximum number of roads a player may build
     * @return the road limit per player
     */
    public static int getMax() {
        return MAX;
    }
}
