// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Resources;

import Player.Player;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	public Player owner;

	/**
	 * 
	 * @return 
	 */
	public abstract int getVictoryPoints();
}
