// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Game;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Class1 {
	/**
	 * 
	 */
	private List players;
	/**
	 * 
	 */
	private Dice dice;
}
