// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Game;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	public int randomizer;

	/**
	 * 
	 * @param randomizer 
	 */
	public void Dice(int randomizer) {
	}

	/**
	 * 
	 * @return 
	 */
	public int roll() {
	}
}
