// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Game;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private List players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * 
	 */
	public void Game() {
	}

	/**
	 * 
	 */
	public void simulate() {
	}

	/**
	 * 
	 */
	private void setup() {
	}

	/**
	 * 
	 */
	private void nextTurn() {
	}

	/**
	 * 
	 */
	private void checkWin() {
	}
}
