// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Game;

import java.util.List;

import Board.Board;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private List players;
	/**
	 * 
	 */
	private Dice dice;

	/**
	 * NEW ATTRIBUTE NOT IN UML!!!!
	 */
	private Board board;

	/**
	 * 
	 */
	public void Game() {
	}

	/**
	 * 
	 */
	public void simulate() {
	}

	/**
	 * 
	 */
	private void setup() {
	}

	/**
	 * 
	 */
	private void nextTurn() {
	}

	/**
	 * 
	 */
	private void checkWin() {
	}

	/**
	 * NEW METHOD NOT IN UML!!!!
	 * 
	 * @return
	 */
	public Board getBoard() {
		return this.board;
	}
}
