// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GameResources;
import static org.junit.Assert.*;
import org.junit.Test;
import java.util.*;

/************************************************************/
/**
 * Unit tests for ResourceType Enum
 * @author Parnia Yazdinia, 400567795, McMaster University
 */
public class ResourceTypeTest {
    @Test
    public void test_values_containsExactlySixConstants() {
        assertEquals("ResourceType should contain exactly 6 constants", 6, ResourceType.values().length);

    }

    @Test
    public void test_values_containsExpectedConstantsInOrder() {
        List<ResourceType> expected = Arrays.asList(ResourceType.BRICK, ResourceType.LUMBER, ResourceType.ORE, ResourceType.WOOL, ResourceType.GRAIN, ResourceType.DESERT);
        assertEquals("ResourceType constants should match the assignment definition", expected, Arrays.asList(ResourceType.values()));
    }

    @Test
    public void test_valueOf_mapsNamesCorrectly() {
        assertEquals(ResourceType.BRICK, ResourceType.valueOf("BRICK"));
        assertEquals(ResourceType.LUMBER, ResourceType.valueOf("LUMBER"));
        assertEquals(ResourceType.ORE, ResourceType.valueOf("ORE"));
        assertEquals(ResourceType.WOOL, ResourceType.valueOf("WOOL"));
        assertEquals(ResourceType.GRAIN, ResourceType.valueOf("GRAIN"));
        assertEquals(ResourceType.DESERT, ResourceType.valueOf("DESERT"));

    }
}
