// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package GameResources;

import Player.Player;

/************************************************************/
/**
 * 
 */
public interface Bank {
	/**
	 * 
	 */
	public Purchasable purchasable;

	/**
	 * 
	 * @param item 
	 * @param player 
	 * @return 
	 */
	public boolean canBuy(Purchasable item, Player player);

	/**
	 * 
	 * @param item 
	 * @param player 
	 */
	public void buy(Purchasable item, Player player);
}
