package Game;

/**
 * Dice interface.
 * Represents a dice abstraction able of producing roll values
 * Allows different implementations of dice to be used within the game
 * 
 * @author Elizabeth Glozman, 400559660, McMaster University
 */
public interface Dice {

    /**
     * Roll the dice and return a value
     * 
     * @return value generated by the dice
     */
    int roll();
}
