// --------------------------------------------------------
// Code generated by Papyrus
// --------------------------------------------------------
package Game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import Board.Board;
import Board.DiceNum;
import Board.Node;
import Board.SetupManager;
import Board.Tile;

import Player.HumanPlayer;
import Player.Player;

import GameResources.City;
import GameResources.ResourceType;
import GameResources.Settlement;
import GameResources.Structure;

/**
 * Orchestrates a Catan game session.
 * Coordinates board creation and set up, turn order and progression, dice
 * rolling,
 * resource distribution, and victory point checking
 *
 * @author Elizabeth Glozman, 400559660 McMaster University
 * @author Taihan Mobasshir, 400578506, McMaster University
 */
public class Game {

    /** list of players in game */
    private final List<Player> players;

    /** Dice for rolling */
    private final Dice dice;

    /** board of tiles and nodes for game */
    private final Board board;

    /** victory point threshold */
    private final int winPoints;

    /** maximum number of rounds before simulation ends */
    private final int maxRounds;

    /** index of current player in list */
    private int currentPlayerIndex = 0;

    /** number of completed rounds */
    private int round = 0;

    /** last roll value */
    private int lastRoll = -1;

    /** winner of the game (null until winner) */
    private Player winner = null;

    /** number of turns played */
    private int turnCounter = 0;

    /** whether the current player has rolled this turn */
    private boolean currentTurnRolled = false;

    /**
     * Construct game with provided board
     *
     * @param players   list of players
     * @param dice      dice implementation
     * @param board     board for the game
     * @param winPoints victory point target
     * @param maxRounds maximum rounds before stopping
     */
    public Game(List<Player> players, Dice dice, Board board,
                int winPoints, int maxRounds) {

        this.players = new ArrayList<>(Objects.requireNonNull(players));
        this.dice = Objects.requireNonNull(dice);
        this.board = Objects.requireNonNull(board);

        if (players.size() < 2 || players.size() > 4) {
            throw new IllegalArgumentException("Need 2–4 players.");
        }

        if (winPoints <= 0) {
            throw new IllegalArgumentException("winPoints must be positive.");
        }

        if (maxRounds < 1 || maxRounds > 8192) {
            throw new IllegalArgumentException("Rounds must be 1–8192.");
        }

        this.winPoints = winPoints;
        this.maxRounds = maxRounds;
    }

    /**
     * Auto created board.
     *
     * @param players   list of players
     * @param dice      dice implementation
     * @param winPoints victory point target
     * @param maxRounds maximum rounds before stopping
     */
    public Game(List<Player> players, Dice dice,
                int winPoints, int maxRounds) {

        this(players, dice, new Board(), winPoints, maxRounds);
    }

    /**
     * Rolls dice using implementation.
     *
     * @return dice roll value
     */
    public int rollMultiDice() {
        return dice.roll();
    }

    /**
     * Runs simulation until winner or max rounds.
     */
    public void simulate() {
        setup();
        printBoard();

        System.out.println(">>> STARTING DICE ROLL SIMULATION <<<\n");

        while (winner == null && round < maxRounds) {
            for (int i = 0; i < players.size() && winner == null; i++) {
                playOneTurn();
            }
            round++;
        }
    }

    /**
     * Setup phase by delegating to SetupManager.
     */
    private void setup() {
        SetupManager setup = new SetupManager(board, System.currentTimeMillis());
        setup.run(players);
        currentPlayerIndex = 0;
    }

    /**
     * Executes one player's turn.
     */
    private void nextTurn() {
        Player current = getCurrentPlayer();
        turnCounter++;
        currentTurnRolled = false;

        if (current instanceof HumanPlayer) {
            current.takeTurn(this);
        } else {
            executeHumanRoll();
            current.takeTurn(this);
        }

        currentPlayerIndex = (currentPlayerIndex + 1) % players.size();
    }

    /**
     * Lets the current player perform the roll for this turn.
     *
     * @return true if a roll happened, false if already rolled
     */
    public boolean executeHumanRoll() {
        if (currentTurnRolled) {
            return false;
        }

        Player current = getCurrentPlayer();
        lastRoll = rollMultiDice();
        currentTurnRolled = true;

        if (dice instanceof MultiDice md) {
            System.out.print("Turn " + turnCounter +
                    "/ Player " + (current.getId() + 1) +
                    ": rolled " + md.getLastDie1() + " + " + md.getLastDie2() +
                    " -> ");
        } else {
            System.out.print("Turn " + turnCounter +
                    ": Player " + (current.getId() + 1) +
                    " rolled " + lastRoll +
                    " -> ");
        }

        printProduction(lastRoll);
        distributeResources(lastRoll);
        System.out.println();

        return true;
    }

    /**
     * Plays a turn and checks for a winner.
     */
    public void playOneTurn() {
        nextTurn();
        checkWin();
    }

    /**
     * Distributes resources for a roll.
     *
     * Robber is still ignored in this version.
     */
    private void distributeResources(int roll) {
        if (roll == 7) {
            return;
        }

        DiceNum dn = board.getTilesForRoll(roll);
        if (dn == null) {
            return;
        }

        for (Tile tile : dn.getTiles()) {
            ResourceType type = tile.getType();
            if (type == null || type == ResourceType.DESERT) {
                continue;
            }

            for (Node node : tile.getNodes()) {
                Structure s = node.getStructure();
                if (s == null) {
                    continue;
                }

                Player owner = s.getOwner();
                if (owner == null) {
                    continue;
                }

                int payout = (s instanceof City) ? 2 : (s instanceof Settlement) ? 1 : 0;

                for (int i = 0; i < payout; i++) {
                    owner.addResource(type);
                }
            }
        }
    }

    /**
     * Checks victory condition.
     */
    private void checkWin() {
        for (Player p : players) {
            int vp = p.calculateVictoryPoints();
            if (vp >= winPoints) {
                winner = p;
                return;
            }
        }
    }

    /**
     * Prints generated board tiles.
     */
    private void printBoard() {
        System.out.println("\n=== GENERATED BOARD (Random Desert) ===");

        for (Tile t : board.getTiles()) {
            System.out.println(t);
        }

        System.out.println("======================================\n");
    }

    /**
     * Prints which tiles produce resources.
     *
     * @param roll dice roll value
     */
    private void printProduction(int roll) {
        if (roll == 7) {
            System.out.print("Producing: [ROBBER — no production] || ");
            return;
        }

        DiceNum dn = board.getTilesForRoll(roll);

        if (dn == null || dn.getTiles().isEmpty()) {
            System.out.print("Producing: [] || ");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Producing: [");

        boolean first = true;

        for (Tile t : dn.getTiles()) {
            ResourceType rt = t.getType();
            if (rt == null || rt == ResourceType.DESERT) {
                continue;
            }

            if (!first) {
                sb.append(" | ");
            }

            sb.append(rt).append(" from Tile ").append(t.getId());
            first = false;
        }

        sb.append("] || ");
        System.out.print(sb.toString());
    }

    /**
     * Returns board used by game.
     *
     * @return board used by game
     */
    public Board getBoard() {
        return board;
    }

    /**
     * Returns dice used in game.
     *
     * @return dice object
     */
    public Dice getDice() {
        return dice;
    }

    /**
     * Returns most recent dice roll total.
     *
     * @return last roll value
     */
    public int getLastRoll() {
        return lastRoll;
    }

    /**
     * Returns completed rounds.
     *
     * @return number of completed rounds
     */
    public int getRound() {
        return round;
    }

    /**
     * Returns unmodifiable view of player list.
     *
     * @return unmodifiable list of players
     */
    public List<Player> getPlayers() {
        return Collections.unmodifiableList(players);
    }

    /**
     * Returns player whose turn it is.
     *
     * @return current player
     */
    public Player getCurrentPlayer() {
        return players.get(currentPlayerIndex);
    }

    /**
     * Indicates if game has ended.
     *
     * @return true if game is over
     */
    public boolean isOver() {
        return winner != null;
    }

    /**
     * Returns winning player or null if unfinished.
     *
     * @return winning player or null
     */
    public Player getWinner() {
        return winner;
    }
}