// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import Game.Game;

/************************************************************/
/**
 * 
 */
public class ComputerPlayer extends Player {
	/**
	 * 
	 */
	private int randomizer;

	/**
	 * 
	 */
	public void ComputerPlayer() {
	}

	/**
	 * 
	 * @param seed 
	 */
	public void ComputerPlayer(int seed) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(Game game) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void setup(Game game) {
	}
}
