// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import Game.Game;
import Resources.City;
import Resources.ResourceType;
import Resources.Road;
import Resources.Settlement;
import Resources.Structure;

/************************************************************/
/**
 * 
 */
public abstract class Player {
	/**
	 * 
	 */
	private static int numPlayers;
	/**
	 * 
	 */
	private static int maxPlayers;
	/**
	 * 
	 */
	private PlayerColor color;
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Structure[] structures;
	/**
	 * 
	 */
	private PlayerHand hand;
	/**
	 * 
	 */
	private Road roads;
	/**
	 * 
	 */
	private int longestRoad;
	/**
	 * 
	 */
	public VictoryPointCalculator victorypointcalculator;

	/**
	 * 
	 */
	public void Player() {
	}

	/**
	 * 
	 * @param game 
	 */
	public abstract void takeTurn(Game game);

	/**
	 * 
	 * @param game 
	 */
	public abstract void setup(Game game);

	/**
	 * 
	 */
	public static void resetNumPlayers() {
	}

	/**
	 * 
	 * @param type 
	 */
	public void addResource(ResourceType type) {
	}

	/**
	 * 
	 * @param type 
	 */
	public void removeResource(ResourceType type) {
	}

	/**
	 * 
	 * @param structure 
	 */
	public void addStructure(Structure structure) {
	}

	/**
	 * 
	 * @return 
	 */

//	/*
//	public int calculateVictoryPoints() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public int getId() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public PlayerColor getColor() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public City[] getCities() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public Settlement[] getSettlements() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public Road[] getRoads() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public String toString() {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public PlayerHand getHand() {
//	}
//
//	/**
//	 *
//	 * @param type
//	 * @return
//	 */
//	public int getResourceAmount(ResourceType type) {
//	}
//
//	/**
//	 *
//	 * @return
//	 */
//	public int getLongestRoad() {
//	}
//	**/
}
