// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import Resources.ResourceType;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class UserHand {
	/**
	 * 
	 */
	private Map count;

	/**
	 * 
	 * @param count 
	 */
	public void UserHand(Map count) {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getCount(ResourceType type) {
		return 0;
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void addCard(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 */
	public void removeCard(ResourceType type, int amount) {
	}
}
