// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import java.util.ArrayList;
import java.util.List;
import GameResources.Structure;

/************************************************************/
/**
 * 
 */
public class VictoryPointCalculator {
    /**
     * 
     * @return
     * @param player
     */
    public static int calculate(Player player) {
        int points = 0;
        List<Structure> structures = new ArrayList<>(player.getCities());
        structures.addAll(player.getSettlements());
        for (Structure structure : structures) {
            points += structure.getVictoryPoints();
        }
        return points;
    }
}
