// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

/************************************************************/
/**
 * 
 */
public class VictoryPointCalculator {
	/**
	 * 
	 * @return 
	 * @param player 
	 */
	public static int calculate(Player player) {
		return 0;
	}
}
