// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import java.util.EnumMap;
import java.util.Map;

import GameResources.ResourceType;

/************************************************************/

/**
 * Represents the hand of a player, tracking the number of each resource type.
 *
 * @author Yojith Sai Biradavolu, McMaster University
 * @version Winter, 2026
 */
public class PlayerHand {
    /**
     * Map of the count of each resource type in the player's hand
     **/
    private final Map<ResourceType, Integer> cardCounter;

    /**
     * Creates a new PlayerHand instance
     */
    public PlayerHand() {
        this.cardCounter = new EnumMap<>(ResourceType.class);
        for (ResourceType type : ResourceType.values()) {
            if (type != ResourceType.DESERT) {
                this.cardCounter.put(type, 0);
            }
        }
    }

    /**
     * Returns the count of the specified resource type in the hand
     *
     * @param type The resource type to count
     * @return The count of the resource type
     */
    public int getCount(ResourceType type) {
        if (type == ResourceType.DESERT) {
            throw new IllegalArgumentException("Cannot get count of DESERT from player hand");
        }
        return this.cardCounter.getOrDefault(type, 0);
    }

	/**
	 * returns the number of cards the player has in their hand
	 *
	 * @return size of hand
	 */
	public int getCount() {
		int totalCards = 0;
		for (int amount : this.cardCounter.values()) {
			totalCards += amount; 
		}
		return totalCards;
	}

    /**
     * Adds the specified amount of the given resource type to the hand
     *
     * @param type   The resource type to add
     * @param amount The amount of the resource type to add
     */
    public void addCard(ResourceType type, int amount) {
        if (type == ResourceType.DESERT) {
            throw new IllegalArgumentException("Cannot add DESERT to player hand");
        }
        if (amount <= 0) {
            throw new IllegalArgumentException("Error: Cannot add " + amount + " of " + type + " to player hand");
        }
        if (this.cardCounter.containsKey(type)) {
            this.cardCounter.put(type, this.cardCounter.get(type) + amount);
        } else {
            this.cardCounter.put(type, amount);
        }
    }

    /**
     * Removes the specified amount of the given resource type from the hand
     *
     * @param type   The resource type to remove
     * @param amount The amount of the resource type to remove
     */
    public void removeCard(ResourceType type, int amount) {
        if (type == ResourceType.DESERT) {
            throw new IllegalArgumentException("Cannot remove DESERT from player hand");
        }
        int inHand = this.cardCounter.get(type);
        if (inHand >= amount) {
            this.cardCounter.put(type, inHand - amount);
        } else {
            throw new IllegalArgumentException("Error: Requested " + amount + " of " + type + " to remove but only " + inHand + " are in hand!");
        }
    }
}
