// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private DiceNum[] diceNums;
	/**
	 * 
	 */
	private Node[] nodes;

	/**
	 * 
	 */
	public void Board() {
	}
}
