// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

import GameResources.ResourceType;

/************************************************************/
/**
 * Represents the specific "Desert" hexagonal tile.
 * This tile is initialized with the explicit DESERT resource type.
 * It serves as a placeholder for desert geometry and produces no resources.
 * @author Taihan Mobasshir, 400578506, McMaster University
 */
public class DesertTile extends Tile {

    /**
     * Constructor for the Desert Tile.
     * * @param id    The unique ID of the tile.
     * @param nodes The 6 corner nodes surrounding this tile.
     */
    public DesertTile(int id, Node[] nodes) {
        // Now passing the explicit ResourceType.DESERT enum instead of null
        super(id, nodes, ResourceType.DESERT);
    }
}