// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

/************************************************************/
/**
 * 
 */
public class DiceNum {
	/**
	 * 
	 */
	private int number;
	/**
	 * 
	 */
	private Node[] tiles;

	/**
	 * 
	 * @param number 
	 * @param tiles 
	 */
	public void DiceNum(int number, Tile[] tiles) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getTiles() {
	}
}
