// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

import GameResources.Road;
import GameResources.Structure;
import Player.Player;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Node left;
	/**
	 * 
	 */
	private Node right;
	/**
	 * 
	 */
	private Node vert;
	/**
	 * 
	 */
	private Player player;
	/**
	 * 
	 */
	private Structure structure;
	/**
	 * 
	 */
	private Road leftRoad;
	/**
	 * 
	 */
	private Road rightRoad;
	/**
	 * 
	 */
	private Road vertRoad;

	/**
	 * 
	 * @param id 
	 */
	public void Node(int id) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getLeft() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getRight() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getVert() {
	}

	/**
	 * 
	 * @param node 
	 */
	public void setLeft(Node node) {
	}

	/**
	 * 
	 * @param node 
	 */
	public void setRight(Node node) {
	}

	/**
	 * 
	 * @param node 
	 */
	public void setVert(Node node) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getPlayer() {
	}

	/**
	 * 
	 * @return 
	 */
	public Structure getStructure() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getLeftRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRighttRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getVertRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node[] openNodes() {
	}
}
