// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

import GameResources.ResourceType;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private ResourceType type;
	/**
	 * 
	 */
	private Node[] nodes;
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @param id 
	 * @param nodes 
	 * @param type 
	 */
	public void Tile(int id, Node[] nodes, ResourceType type) {
	}

	/**
	 * 
	 */
	private void nodeConnector() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getType() {
	}
}
