// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Board;

import Resources.ResourceType;

/************************************************************/
/**
 *
 */
public class Tile {
	/**
	 *
	 */
	private ResourceType type;
	/**
	 *
	 */
	private Node[] nodes;
	/**
	 *
	 */
	private int id;

	/**
	 *
	 * @param id
	 * @param nodes
	 * @param type
	 */
	public Tile(int id, Node[] nodes, ResourceType type) {
		this.id = id;

		// VALIDATION: Ensure the passed array is the correct size
		if (nodes == null || nodes.length != 6) {
			throw new IllegalArgumentException("A tile requires exactly 6 valid nodes.");
		}
		this.nodes = nodes;
		nodeConnector();
		this.type = type;
	}

	/**
	 *
	 */
	private void nodeConnector() {
		nodes[0].setVert(nodes[1]);
		nodes[1].setLeft(nodes[2]);
		nodes[2].setLeft(nodes[3]);
		nodes[3].setVert(nodes[4]);
		nodes[4].setRight(nodes[5]);
		nodes[5].setRight(nodes[0]);
	}

	/**
	 *
	 * @return
	 */
	public ResourceType getType() {
		return this.type;
	}

	// Add inside Tile.java
	public int getId() { return id; }

	@Override
	public String toString() {
		String typeStr = (this.type == null) ? "DESERT" : this.type.toString();
		return String.format("Tile ID: %-2d | Resource: %-8s", id, typeStr);
	}
}
