// --------------------------------------------------------
// Code generated by Papyrus
// --------------------------------------------------------
package Game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import Board.Board;
import Board.DiceNum;
import Board.Tile;
import Board.Node;
import Board.SetupManager;

import Player.Player;

import GameResources.ResourceType;
import GameResources.Structure;
import GameResources.City;
import GameResources.Settlement;

/**
 * Coordinates board creation and set up, turn order and progression, dice
 * rolling,
 * resource distribution, and victory point checking
 *
 * @author Elizabeth Glozman, 400559660 McMaster University
 * @author Taihan Mobasshir, 400578506, McMaster University
 */
public class Game {
    private static final int TIMEOUT = 2000;

    @Before
    public void resetPlayerIds() {
        Player.resetNumPlayers();
    }

    /**
     * Simple fixed dice for testing.
     */
    private static class FixedDice implements Dice {
        private final int value;
        FixedDice(int value) {
            this.value = value;
        }
        @Override
        public int roll() {
            return value;
        }
    }

    /**
     * Simple test player used only for JUnit tests.
     */
    private static class TestPlayer extends Player {
        public TestPlayer() {
            super();
        }
        @Override
        public void takeTurn(Game game) {
        }
        @Override
        public void setup(Game game) {
        }
    }

    /**
     * Boundary test: constructor accepts the minimum valid number of players.
     */
    @Test(timeout = TIMEOUT)
    public void minPlayersAccepted() {
        Game game = new Game(makePlayers(2), new FixedDice(6), 10, 5);
        assertEquals("game stores 2 players", 2, game.getPlayers().size());
    }

    /**
     * Boundry test: constrcutor accepts the maximum valid number of players .
     */
    @Test(timeout = TIMEOUT)
    public void maxPlayerAccepted(){
        Dice dice = mock(Dice.class);
        List<Player> players = Arrays.asList(
                makePlayer(0, 0),
                makePlayer(1, 0),
                makePlayer(2, 0),
                makePlayer(3, 0)
        );
        Game game = makeGame(players, dice, 10, 5);
        assertEquals("game stores four players", 4, game.getPlayers().size());
    }

    @Test(timeout = TIMEOUT)
    public void badConstructorInputs(){
        List<Player> onePlayer = Arrays.asList(makePlayer(0, 0));
        List<PLayer> fivePlayers = Arrays.asList(
                makePlayer(0, 0), makePlayer(1, 0), makePlayer(2, 0),
                makePlayer(3, 0), makePlayer(4, 0)
        );

        assertThrows(IllegalArgumentException.class, () -> new Game(onePlayer, dice, board, 10, 5));
    }
    
}