// --------------------------------------------------------
// Code generated by Papyrus
// --------------------------------------------------------
package Game;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import Board.Board;
import Board.DiceNum;
import Board.Tile;
import Board.Node;
import Board.SetupManager;

import Player.Player;

import GameResources.ResourceType;
import GameResources.Structure;
import GameResources.City;
import GameResources.Settlement;

/**
 * Unit tests for Game.
 * @author Parnia Yazdinia, 400567795, McMaster University
 */
public class Game {
    private static final int TIMEOUT = 2000;

    @Before
    public void resetPlayers() {
        Player.resetNumPlayers();
    }

    /**
     * Simple fixed dice for testing.
     */
    private static class FixedDice implements Dice {
        private final int value;

        public FixedDice(int value) {
            this.value = value;
        }

        @Override
        public int roll() {
            return value;
        }
    }

    /**
     * Simple player used for testing.
     */
    private static class TestPlayer extends Player {

        public TestPlayer() {
            super();
        }

        @Override
        public void takeTurn(Game game) {
            // no action needed
        }

        @Override
        public void setup(Game game) {
            // no action needed
        }
    }

    /**
     * Helper method to create a list of test players
     * @param count The amount of players
     * @return the amount of players
     */
    private List<Player> makePlayers(int count) {
        List<Player> players = new ArrayList<Player>();
        for (int i = 0; i < count; i++) {
            players.add(new TestPlayer());
        }
        return players;
    }

    /**
     * Boundary test: constructor accepts minimum valid number of players.
     */
    @Test(timeout = TIMEOUT)
    public void minPlayersAccepted() {
        Game game = new Game(makePlayers(2), new FixedDice(6), 10, 5);
        assertEquals("game stores 2 players", 2, game.getPlayers().size());
    }

    /**
     * Boundary test: constructor accepts maximum valid number of players.
     */
    @Test(timeout = TIMEOUT)
    public void maxPlayersAccepted() {
        Game game = new Game(makePlayers(4), new FixedDice(6), 10, 5);
        assertEquals("game stores 4 players", 4, game.getPlayers().size());
    }

    /**
     * Tests the initial state right after construction.
     */
    @Test(timeout = TIMEOUT)
    public void initialState() {
        List<Player> players = makePlayers(2);
        Game game = new Game(players, new FixedDice(8), 10, 5);

        assertEquals("round starts at 0", 0, game.getRound());
        assertEquals("last roll starts at -1", -1, game.getLastRoll());
        assertEquals("first player starts first", players.get(0), game.getCurrentPlayer());
        assertFalse("game is not over at start", game.isOver());
        assertNull("winner starts as null", game.getWinner());
        assertNotNull("board is created", game.getBoard());
        assertNotNull("dice is stored", game.getDice());
    }

    /**
     * Tests that rollMultiDice delegates to the dice object.
     */
    @Test(timeout = TIMEOUT)
    public void multiDiceReturnsDiceRoll() {
        Game game = new Game(makePlayers(2), new FixedDice(9), 10, 5);
        assertEquals("rollMultiDice returns dice roll", 9, game.rollMultiDice());
    }

    /**
     * Tests that player list returned is not changable.
     */
    @Test(timeout = TIMEOUT)
    public void playersListIsUnmodifiable() {
        Game game = new Game(makePlayers(2), new FixedDice(6), 10, 5);

        try {
            game.getPlayers().add(new TestPlayer());
            fail("Expected UnsupportedOperationException");
        } catch (UnsupportedOperationException e) {
            // expected
        }
    }

    /**
     * Constructor rejects too few players.
     */
    @Test(timeout = TIMEOUT, expected = IllegalArgumentException.class)
    public void tooFewPlayersRejected() {
        new Game(makePlayers(1), new FixedDice(6), 10, 5);
    }

    /**
     * Constructor rejects too many players.
     */
    @Test(timeout = TIMEOUT, expected = IllegalArgumentException.class)
    public void tooManyPlayersRejected() {
        new Game(makePlayers(5), new FixedDice(6), 10, 5);
    }

    /**
     * Boundry test: win points must be positive.
     */
    @Test(timeout = TIMEOUT, expected = IllegalArgumentException.class)
    public void badWinPointsRejected() {
        new Game(makePlayers(2), new FixedDice(6), 0, 5);
    }


    /**
     * Boundry test: maximum rounds must be in the valid range.
     */
    @Test(timeout = TIMEOUT, expected = IllegalArgumentException.class)
    public void badRoundsRejected() {
        new Game(makePlayers(2), new FixedDice(6), 10, 0);
    }

    /**
     * Tests that null dice is rejected.
     */
    @Test(timeout = TIMEOUT, expected = NullPointerException.class)
    public void nullDiceRejected() {
        new Game(makePlayers(2), null, 10, 5);
    }

    /**
     * Tests that null players list is rejected.
     */
    @Test(timeout = TIMEOUT, expected = NullPointerException.class)
    public void nullPlayersRejected() {
        new Game(null, new FixedDice(6), 10, 5);
    }
}












    @Test(timeout = TIMEOUT)
    public void badConstructorInputs(){
        List<Player> onePlayer = Arrays.asList(makePlayer(0, 0));
        List<PLayer> fivePlayers = Arrays.asList(
                makePlayer(0, 0), makePlayer(1, 0), makePlayer(2, 0),
                makePlayer(3, 0), makePlayer(4, 0)
        );

        assertThrows(IllegalArgumentException.class, () -> new Game(onePlayer, dice, board, 10, 5));
    }

}