// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import java.util.Map;
import static org.junit.Assert.*;
import org.junit.Test;
import GameResources.ResourceType;

/************************************************************/
/**
 * Test for PlayerHand
 * @author Yojith Sai Biradavolu, McMaster University
 * @version Winter, 2026
 */
public class PlayerHandTest {

    @Test
    public void test_allResourceCountsStartAtZero() {
        PlayerHand hand = new PlayerHand();
        for (ResourceType type : ResourceType.values()) {
            assertEquals("New hand shoul start with 0 for " + type, 0, hand.getCount(type));
        }
    }

    @Test
    public void test_addCard_increasesCount() {
        PlayerHand hand = new PlayerHand();
        hand.addCard(ResourceType.BRICK, 2);
        assertEquals("BRICK count should increase by 2", 2, hand.getCount(ResourceType.BRICK));

        hand.addCard(ResourceType.BRICK, 3);
        assertEquals("BRICK count shoud now be 5", 5, hand.getCount(ResourceType.BRICK));
    }

    @Test
    public void test_removeCard_decreasesCount() {
        PlayerHand hand = new PlayerHand();

        hand.addCard(ResourceType.WOOL, 4);
        hand.removeCard(ResourceType.WOOL, 1);
        assertEquals("WOOL should decrease from 4 to 3", 3, hand.getCount(ResourceType.WOOL));
    }

    @Test(expected = IllegalArgumentException.class)
    public void test_removeCard_moreThanInHand() {
        PlayerHand hand = new PlayerHand();

        hand.addCard(ResourceType.GRAIN, 1);
        hand.removeCard(ResourceType.GRAIN, 2);
    }

}

