// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Player;

import java.util.ArrayList;
import java.util.List;
import GameResources.Structure;

/************************************************************/
/**
 * Tests for VictoryPointCalculator
 */
public class VictoryPointCalculatorTest {
    private static class StubPlayer extends Player{
        @Override public void takeTurn(Game game){}
        @override public void setup(Game game) {}
    }
    @Before
    public void resetStaticCounter(){
        Player.resetNumPlayers();
    }
    @Test
    public void test_calculate_emptyPlayer_isZero(){
        Player p = new StubPlayer();
        assertEquals("No stuctures implies 0 VP", 0, p.calculateVictoryPoints());
    }

    @Test
    public void test_calculate_settlementAndCity(){
        Player p = new StubPlayer();

        p.addStructure(new Settlement());
        p.addStructure(new City());

        int vp = p.calculateVictoryPoints();
        assertEquals("1 Settlement with 2 City should be 3 VP", 3, vp);
    }
}
