// --------------------------------------------------------
// Code generated by Papyrus
// --------------------------------------------------------
package TestGame;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;

import Board.Tile;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import Game.Dice;
import Game.Game;
import Player.Player;

/**
 * Unit tests for Game.
 *
 * @author Parnia Yazdinia, 400567795, McMaster University
 */
public class TestGame {
    private static final int TIMEOUT = 2000;

    @BeforeEach
    public void resetPlayers() {
        Player.resetNumPlayers();
    }

    /**
     * Simple fixed dice for testing.
     */
    private static class FixedDice implements Dice {
        private final int value;

        public FixedDice(int value) {
            this.value = value;
        }

        @Override
        public int roll() {
            return value;
        }
    }

    /**
     * Simple player used for testing.
     */
    private static class TestPlayer extends Player {

        public TestPlayer() {
            super();
        }

        @Override
        public void takeTurn(Game game) {
            // no action needed
        }

        @Override
        public void setup(Game game) {
            // no action needed
        }

        @Override
        public void robberDiscard() {
            // no action needed
        }

        @Override
        public Tile setRobber(List<Tile> tiles) {
            return null;
        }

    }

    /**
     * Helper method to create a list of test players
     *
     * @param count The amount of players
     * @return list of players
     */
    private List<Player> makePlayers(int count) {
        List<Player> players = new ArrayList<Player>();
        for (int i = 0; i < count; i++) {
            players.add(new TestPlayer());
        }
        return players;
    }

    /**
     * Boundary test: constructor accepts minimum valid number of players.
     */
    @Test
    @Timeout(TIMEOUT)
    void minPlayersAccepted() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(6);
        Game game = new Game(players, dice, 10, 5);
        assertEquals(2, game.getPlayers().size(), "game stores 2 players");
    }

    /**
     * Boundary test: constructor accepts maximum valid number of players.
     */
    @Test
    @Timeout(TIMEOUT)
    void maxPlayersAccepted() {
        List<Player> players = makePlayers(4);
        Dice dice = new FixedDice(6);
        Game game = new Game(players, dice, 10, 5);
        assertEquals(4, game.getPlayers().size(), "game stores 4 players");
    }

    /**
     * Tests the initial state right after construction.
     */
    @Test
    @Timeout(TIMEOUT)
    void initialState() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(6);
        Game game = new Game(players, dice, 10, 5);

        assertEquals(0, game.getRound(), "round starts at 0");
        assertEquals(-1, game.getLastRoll(), "last roll starts at -1");
        assertEquals(players.get(0), game.getCurrentPlayer(), "first player starts first");
        assertFalse(game.isOver(), "game is not over at start");
        assertNull(game.getWinner(), "winner starts as null");
        assertNotNull(game.getBoard(), "board is created");
        assertNotNull(game.getDice(), "dice is stored");
    }

    /**
     * Tests that rollMultiDice delegates to the dice object.
     */
    @Test
    @Timeout(TIMEOUT)
    void multiDiceReturnsDiceRoll() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(9);
        Game game = new Game(players, dice, 10, 5);
        assertEquals(9, game.rollMultiDice(), "rollMultiDice returns dice roll");
    }

    /**
     * Tests that player list returned is not changable.
     */
    @Test
    @Timeout(TIMEOUT)
    void playersListIsUnmodifiable() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(6);
        Game game = new Game(players, dice, 10, 5);

        try {
            game.getPlayers().add(new TestPlayer());
            fail("Expected UnsupportedOperationException");
        } catch (UnsupportedOperationException e) {
            // expected
        }
    }


    /**
     * Boundary test: win points must be positive.
     */
    @Test
    @Timeout(TIMEOUT)
    void badWinPointsRejected() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(6);
        assertThrows(IllegalArgumentException.class, () -> new Game(players, dice, 0, 5), "Win points must be positive");
    }

    /**
     * Boundary test: maximum rounds must be in the valid range.
     */
    @Test
    @Timeout(TIMEOUT)
    void badRoundsRejected() {
        List<Player> players = makePlayers(2);
        Dice dice = new FixedDice(6);
        assertThrows(IllegalArgumentException.class, () -> new Game(players, dice, 10, 0), "Rounds must be in the valid range");
    }

    /**
     * Tests that null dice is rejected.
     */
    @Test
    @Timeout(TIMEOUT)
    void nullDiceRejected() {
        assertThrows(NullPointerException.class, () -> new Game(makePlayers(2), null, 10, 5), "Null dice is not allowed");
    }

    /**
     * Tests that null players list is rejected.
     */
    @Test
    @Timeout(TIMEOUT)
    void nullPlayersRejected() {
        Dice dice = new FixedDice(6);
        assertThrows(NullPointerException.class, () -> new Game(null, dice, 10, 5), "Null players list is not allowed");
    }

    /**
     * Tests that single player is not allowed
     */
    @Test
    @Timeout(TIMEOUT)
    void singlePlayerRejected() {
        List<Player> players = new ArrayList<Player>();
        players.add(new TestPlayer());
        Dice dice = new FixedDice(6);
        assertThrows(IllegalArgumentException.class, () -> new Game(players, dice, 10, 5), "Single player is not allowed");
    }

    /**
     * Simple sanity check for simulate
     */
    @Test
    @Timeout(TIMEOUT)
    void TestSimulate() {
        Game game = new Game(makePlayers(2), new FixedDice(6), 10, 10);
        assertDoesNotThrow(() -> game.simulate(), "simulate does not throw any errors");
    }
}
